"""add estimate table

Revision ID: 1419df69d2de
Revises:
Create Date: 2024-01-15 01:52:09.035396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "1419df69d2de"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estimate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("responce_message_id", sa.Integer(), nullable=False),
        sa.Column("responce_chat_id", sa.Integer(), nullable=False),
        sa.Column("query_text", sa.String(), nullable=False),
        sa.Column("responce_text", sa.String(), nullable=False),
        sa.Column("responce_urls", sqlite.JSON(), nullable=True),
        sa.Column("enhancement_text", sa.String(), nullable=False),
        sa.Column("enhancement_urls", sqlite.JSON(), nullable=False),
        sa.Column(
            "estimate",
            sa.Enum("good", "bad", native_enum=False),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("estimate")
    # ### end Alembic commands ###
