"""init

Revision ID: b5fd4e3555cb
Revises:
Create Date: 2024-01-16 02:03:26.405881

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b5fd4e3555cb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
